config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # Sets the root of the website:
  root 'projects#index'
  # Regular routes:
  get '/about' => 'pages#about'
  get '/contact' => 'pages#contact'
  post '/contact' => 'pages#message'
  get '/signup' => 'users#new'
  get '/login' => 'sessions#new'
  get '/new' => 'projects#new'
  get '/settings' => 'users#settings'
  get '/settings/account' => 'users#account'
  get '/account' => 'users#show'
  delete '/logout' => 'sessions#destroy'
  get '/settings/account' => 'users#update'
  get '/upload' => 'images#new'
  get '/projects' => 'projects#show'
  get '/label' => 'labels#new'
  get '/dashboard' => 'projects#dashboard'
  post 'create_question' => 'projects#create_question'
  get '/retrieve' => 'projects#retrieve'
  get '/saveanswer' => 'labels#saveanswer'
  
  # Resources:
  resources :projects
  resources :users
  resources :sessions
  resources :labels
  resources :images
  resources :question
  
end

app/models/project.rb
class Project < ApplicationRecord
    belongs_to :user
    has_many :images, dependent: :destroy
    has_many :questions, dependent: :destroy
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  #      render plain: params[:project].inspect
    def index
        @projects = Project.all
        render 'index'
    end
  
    def show
      @project = Project.find(params[:id])
      @show_edit = false;
      if current_user
        if (@project.user_id == current_user.id || current_user.rank == "admin") 
          @show_edit = true;
        end
      end
    end
  
    def new
      if current_user
      else
        redirect_to '/login'
      end
    end
  
    def create
      # Cria um Projeto, altera o seu user_id pro id do usuário e salva na DB.
      # Em caso de sucesso, faz upload das imagens e redireciona pra página de pergunta.
      @project = Project.new(project_params)
      @project.user_id = current_user.id
      if (@project.save)
          params[:project][:files].each { |upload|
            @image = @project.images.create()
            @image.file.attach(upload)
            @image.nviews = 0
            @image.save!
          }
          render 'newquestion' and return
      else
        render 'new'
      end
    end
    
    def create_question
      # Cadastra na DB uma pergunta de um projeto.
      @project = Project.find(params[:question][:project_id])
      @question = Question.new(question_params)
      @question.project_id = @project.id
      @question.nviews = 0
      if (@question.save)
        params[:question][:text].each { |text|
          @answer_opt = AnswerOpt.new()
          @answer_opt.text = text
          @answer_opt.question_id = @question.id
          @answer_opt.nanswers = 0
          @answer_opt.save!
          }
        redirect_to @project and return
      end
    end
  
    def edit
      @project = Project.find(params[:id])
      @project.user_id = current_user.id
    end
  
    def update
      @project = Project.find(params[:id])
      if(@project.update(project_params))
        redirect_to @project
      else
        render 'edit'
      end
    end
  
    def destroy
      @project = Project.find(params[:id])
      @images = Image.where('project_id = ?', @project.id)
      @question = Question.where('project_id = ?', @project.id).first
      @opts = AnswerOpt.where('question_id = ?', @question.id)
      
      #
      @opts.each do |opt|
        opt.destroy
      end
      @images.each do |image|
        @answers = Answer.where('image_id = ?', image.id);
        @answers.each do |answer|
          answer.destroy
        end
        image.destroy
      end      
      @question.destroy
      @project.destroy
      redirect_to '/dashboard'
    end
  
    def dashboard
      @projects = Project.all
      render 'dashboard'
    end

    private def project_params
      params.require(:project).permit(:name, :description)
    end
  
    private def question_params
      params.require(:question).permit(:description, :text, :project_id)
    end
  
    private def image_params
      params.require(:project).permit(:file)
    end

    def dashboard
      @projects = Project.where('user_id = ?', current_user.id)      
    end

    def retrieve
      @images = Image.where('project_id = ?', params[:pid])
      @question = Question.where('project_id = ?', params[:pid]).first
      @opts = AnswerOpt.where('question_id = ?', @question.id)
      render 'retrieve'
    end 
end

app/views/projects/dashboard.html.haml
%main{:role => "main"}
  .album.py-5
    .container
      .row
        - @projects.each do |project|
          - @image = project.images.sample
          .col-md-4
            .card.mb-4.box-shadow
              = image_tag(@image.file, alt: "Imagem da pergunta", class: 'card-img-top')
              /%img.card-img-top{:alt => "Card image cap", "data-src" => @image.file}/
              .card-body.text-dark
                %p.card-text= project.name                
                %hr
                %p.card-text= project.description
                /%p.card-text= project.user_id
                .text-center     
                  = link_to "Obter dados", :controller => "projects", :action => "retrieve", :pid => project.id
                  %button.btn.btn-dark{:type => "button"}= link_to "Ver mais", project_path(project), class: 'text-light'
                %hr
                %small.text-muted Criado em
                %small.text-muted= project.created_at.strftime("%-d/%-m/%y às %H:%M")               
              

app/views/projects/edit.html.haml
.row.justify-content-center
  %main.inner.cover{:role => "main"}
    %form.form-signin          
    = form_for :project, :url => {:controller => 'projects', :action => 'update'}, :method => "patch" do |f|
      %h1.h3.mb-3.font-weight-normal Atualizar projeto
      %label.sr-only{:for => "email"} Título            
      /= f.text_field :title, class: 'form-control', :placeholder => "Título", :required => ""
      %label.sr-only{:for => "password"} Descrição curta do conjunto de imagens
      = f.text_area :description, class: 'form-control', :placeholder => "Descrição", :required => ""            
      %a.card-link{:href => "#"}
      %button.btn.btn-lg.btn-primary.btn-block{:type => "button"}= link_to "Voltar", project_path(@project), class: 'text-light'
      %button.btn.btn-lg.btn-primary.btn-block{:type => "submit"} Enviar

app/views/projects/index.html.haml
- if current_user
  -# USUÁRIO LOGADO
  %main.text-center.card-trans.narrow
    %h1.cover-heading MONOLITO
    %p.lead Inteligência gera inteligência
    %main.text-center
      %p.lead
        %a.btn.btn-primary{:href => "/label"} 
          %i.fa.fa-pencil
          Colabore
        %a.btn.btn-warning{:href => "/new"} 
          %i.fa.fa-plus
          Crie o seu projeto
- else
  -# USUÁRIO NÃO LOGADO
  %main.text-center.card-trans.wide
    %h1.cover-heading MONOLITO
    %p.lead Inteligência gera inteligência
  %main.card-trans.wide
    %span.text-center
    %h3 Quem somos
    %p Uma plataforma que conecta projetos de inteligências artificiais a pessoas. 

    %h3 Por que isso importa
    %p Na área de aprendizado de máquina, um grande desafio é ter em mãos um conjunto de dados rotulados suficiente para que sirva de ‘gabarito’ para o algoritmo - seja durante o desenvolvimento, com o treinamento da inteligência artificial, seja depois, com a validação da acurácia.

    %h3 Como funciona
    %p Se você é um desenvolvedor, aqui você pode depositar seu conjunto de dados, indicar o que precisa ser classificado ou avaliado com relação a esses dados e obter a um custo justo um amplo espectro de respostas dadas por usuários comuns, recebendo de volta em pouco tempo seus dados devidamente rotulados para uso em sua aplicação.
  
    %h3 Se interessou? 
    
    %main.text-center
      %p.lead
        %a.btn.btn-primary{:href => "/label"} 
          %i.fa.fa-pencil
          Colabore
        %a.btn.btn-warning{:href => "/new"} 
          %i.fa.fa-plus
          Crie o seu projeto   

app/views/projects/new.html.haml
.card-trans.wide
  = form_for :project, :url => {:controller => 'projects', :action => 'create'} do |f|
    %h1.text-center Novo projeto
    %label.sr-only{:for => "name"} Título            
    = f.text_field :name, class: 'form-control', :placeholder => "Título", :required => ""
    %label.sr-only{:for => "description"} Descrição curta do conjunto de imagens
    = f.text_area :description, class: 'form-control', :placeholder => "Descrição (opcional)"
    .image-upload
      = f.file_field :files, :id => "files", multiple: true, class: 'form-control', :placeholder => "Imagens", :required => ""
    .text-center
      .card-trans
        %label{:for => "files"} 
          %i.fa.fa-file.fa-5x
    %br

    %button.btn.btn-lg.btn-primary.btn-block{:type => "submit"} Continuar
      

app/views/projects/newquestion.html.haml
.card.center-card.card-text
  %h1.text-center Preencha uma pergunta
  %form.form-signin
  = form_for :question, :url => {:controller => 'projects', :action => 'create_question'} do |f|
    = f.text_field :description, class: 'form-control', :placeholder => "O que você vê na imagem?", :required => ""
    = f.text_field :text, multiple: true, class: 'form-control', :placeholder => "Um pato", :required => ""
    = f.text_field :text, multiple: true, class: 'form-control', :placeholder => "Um leão", :required => ""
    = f.text_field :text, multiple: true, class: 'form-control', :placeholder => "Um crocodilo", :required => ""
    = f.text_field :text, multiple: true, class: 'form-control', :placeholder => "O Chapolim colorado", :required => ""
    = f.text_field :text, multiple: true, class: 'form-control', :placeholder => "Fora Temer", :required => ""
    = f.hidden_field :project_id, value: @project.id
    .row.justify-content-center
      &nbsp
      %button.btn.btn-lg.btn-success{:type => "submit"} Finalizar
      

      

app/views/projects/retrieve.html.haml
%main.inner.cover.post-content.text-dark.text-center{:role => "main"}
  %h2 Resultado das respostas dos usuários
  .table-responsive
    %table#datatable.table.table-striped.table-sm
      %thead
        %tr
          %th Imagem
          -@opts.each do |opt|
            %th= opt.text
      %tbody
        -@images.each do |image|
          %tr
            %td
              =image_tag(image.file, alt: "Imagem da pergunta", class: 'img-mini')
              = image.id
            -@opts.each do |option|
              -if option.image_id == image.id
                %td= option.nanswers
              -else
                %td= 0
  %a.badge.badge-success.text-light{:download => "answers.xls", :href => "#", :onclick => "return ExcellentExport.excel(this, 'datatable', 'Sheet Name Here');"} Exportar para o Excel
  %a.badge.badge-dark.text-light{:download => "answers.csv", :href => "#", :onclick => "return ExcellentExport.csv(this, 'datatable');"} Exportar para CSV
  %br 
  %br
  %br
  %small.font-italic
    Algoritmo 'excellentexport' para exportar os dados por 
    %a{:href => 'https://github.com/jmaister/'} jmaister
    , licenciado sob a Licença do MIT.

app/views/projects/show.html.haml
%main.card.center-card
  - @image = @project.images.sample
  .text-center
    = image_tag(@image.file, alt: "Imagem da pergunta", class: 'img-fluid', style: 'height:300px;width:auto;')

  /= image_tag(@image.file, alt: "Imagem da pergunta", class: 'card-img-top', style: 'height:auto;width:600px;' )
  .card-body.text-dark
    %h1 
      = @project.name                
    %hr
    %p.card-text= @project.description
  .card-body.text-center
    - if @show_edit
      %a.card-link{:href => "#"}
      = link_to "Voltar", '/dashboard', :class => 'btn btn-dark'
      %a.card-link{:href => "#"}
      = link_to "Editar", edit_project_path(@project), :class => 'btn btn-dark'
      %a.card-link{:href => "#"}
      = link_to "Deletar", project_path(@project), 
                method: :delete, data: { confirm: 'Are you sure?' },
                :class => 'btn btn-danger'